# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from asyncy.rpc import http_proxy_pb2 as asyncy_dot_rpc_dot_http__proxy__pb2


class HttpProxyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RunStory = channel.unary_unary(
        '/HttpProxy/RunStory',
        request_serializer=asyncy_dot_rpc_dot_http__proxy__pb2.Request.SerializeToString,
        response_deserializer=asyncy_dot_rpc_dot_http__proxy__pb2.Response.FromString,
        )


class HttpProxyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RunStory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HttpProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RunStory': grpc.unary_unary_rpc_method_handler(
          servicer.RunStory,
          request_deserializer=asyncy_dot_rpc_dot_http__proxy__pb2.Request.FromString,
          response_serializer=asyncy_dot_rpc_dot_http__proxy__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HttpProxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
