# -*- coding: utf-8 -*-
import enum


@enum.unique
class ReleaseState(enum.Enum):
    QUEUED = 'QUEUED'
    DEPLOYING = 'DEPLOYING'
    DEPLOYED = 'DEPLOYED'
    TERMINATING = 'TERMINATING'
    TERMINATED = 'TERMINATED'
    NO_DEPLOY = 'NO_DEPLOY'
    FAILED = 'FAILED'
    TEMP_DEPLOYMENT_FAILURE = 'TEMP_DEPLOYMENT_FAILURE'
    SKIPPED_CONCURRENT = 'SKIPPED_CONCURRENT'
    TIMED_OUT = 'TIMED_OUT'
